title: Ferramentas e diretrizes para Ciência Aberta
logo: /assets/img/ibict.jpeg
description: Página em construção para disseminação de ferramentas e diretrizes para promoção da Ciência Aberta
show_downloads: true
google_analytics:
theme: jekyll-theme-minimal
